### PR TITLE
Add a top area box panel

### PR DESCRIPTION
**Pull request by blink1073**
This is needed for https://github.com/jupyter/jupyterlab/pull/195.

### CODE REVIEW

**Comment by sccolbert** [comment]
Why is this needed? The top panel already exists. Just use flexbox to lay out the contents.

**Comment by blink1073** [comment]
There is no way to *add* to the top panel currently, it is a no-op.  I can change it back to a `Panel` though.

**Comment by sccolbert** [comment]
Yeah, sorry. I updated my comment.

**Comment by blink1073** [comment]
Updated.

**Pull request merged**
