### PR TITLE
CSS plugin

### PR DESCRIPTION
**Pull request by blink1073**
Tested with SystemJS and StealJS.
Accepts a relative path to the CSS file (from the package root).

### CODE REVIEW

**Comment by blink1073** [comment]
Tested using this [file](https://github.com/blink1073/phosphor-plugins/blob/css-test/examples/src/bar/index.js)

**Comment by sccolbert** [comment]
What are your thoughts about requiring the full path? Do you think its worth the effort to try to make relative paths somehow work?

**Comment by blink1073** [comment]
I looked into it, couldn't see an easy way other than if we auto-magically convert relative paths specified in the `phosphor-plugin` spec to `package/path`.

**Comment by blink1073** [comment]
or if an `extension` had a `plugin` or `package` attribute.

**Comment by sccolbert** [comment]
I'd like to be able to support relative paths, but then dynamically registering a CSS extension would be difficult.

We'll also hit this issue for relative paths contained in data JSON files.

Which makes me wonder, for consistencies sake, if we should support relative paths at all in a plugin spec. This has the side effect of allowing a plugin spec to load code from another package.

**Comment by blink1073** [comment]
Updated to use relative path.

**Pull request closed without merging**
