### PR TITLE
Add a debug print to after_success

### PR DESCRIPTION
**Pull request by blink1073**
The intent is to rebuild the docs after merging this.  Ref #76.

### CODE REVIEW

**Comment by sccolbert** [comment]
The docs probably won't build after merging, because TS 1.8 will get picked up, and typedoc will fail on that version.

**Comment by blink1073** [comment]
As long as we don't *use* any TS 1.8 syntax, it should work with TypeDoc's bundled TS 1.6.

**Comment by sccolbert** [comment]
Ah. Good point. But if all you want is a rebuild. I can just kick travis.

**Comment by blink1073** [comment]
The docs only push after merging a PR.

**Comment by willingc** [comment]
Perhaps just link here https://phosphorjs.github.io/docs.html in the README if it is the same content.

**Pull request merged**
