### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jasongrout**
Update phosphor-command and phosphor-widget dependencies.

### CODE REVIEW

**Comment by jasongrout** [comment]
It looks like #53 includes this update, so this should probably be discarded if that is merged first.

**Comment by jasongrout** [comment]
(Well, #53 has the major update, the phosphor-command one.  It doesn't have the phosphor-widget one.)

**Comment by sccolbert** [comment]
There's no functional changes to the phosphor-widget one. We only released `rc.1` because the `browserify` meta key in `package.json` was causing problems for the IBM guys.

**Comment by jasongrout** [comment]
Okay. It looked like it was a drop-in replacement.

**Comment by blink1073** [comment]
Merged #53 instead.

**Pull request closed without merging**
